"""Generate shareable static pages from the text files in posts/."""
from datetime import date
from html import escape
from pathlib import Path
from urllib.parse import quote
import re
import sys
import json
from xml.etree import ElementTree as ET

MARKER = '<!-- Generated by notes/build.py; edit the source .txt files instead. -->'


def parse_post(text, filename):
    lines = text.lstrip('\ufeff').splitlines()
    if '---' not in lines:
        raise ValueError('add a --- line between the header and article')
    divider = lines.index('---')
    fields = {}
    for line in lines[:divider]:
        if not line.strip():
            continue
        key, separator, value = line.partition(':')
        if not separator or key not in ('Title', 'Order', 'Date', 'Updated', 'Summary', 'Author', 'Status', 'Image', 'Image Alt') or key in fields:
            raise ValueError(f'invalid header: {line}')
        fields[key] = value.strip()
    for key in ('Title', 'Summary'):
        if not fields.get(key):
            raise ValueError(f'add a {key}: line')
    fields['order'] = None
    if fields.get('Order'):
        if not re.fullmatch(r'[0-9]+', fields['Order']) or int(fields['Order']) < 1:
            raise ValueError('Order must be a positive whole number (1, 2, 3, ...)')
        fields['order'] = int(fields['Order'])
    fields['date'] = None
    if fields.get('Date'):
        if not re.fullmatch(r'\d{4}-\d{2}-\d{2}', fields['Date']):
            raise ValueError('Date must use YYYY-MM-DD')
        fields['date'] = date.fromisoformat(fields['Date'])
    fields['updated'] = fields['date']
    if fields.get('Updated'):
        if not re.fullmatch(r'\d{4}-\d{2}-\d{2}', fields['Updated']):
            raise ValueError('Updated must use YYYY-MM-DD')
        fields['updated'] = date.fromisoformat(fields['Updated'])
        if fields['date'] and fields['updated'] < fields['date']:
            raise ValueError('Updated cannot be earlier than Date')
    fields['Status'] = fields.get('Status', 'published').lower()
    if fields['Status'] not in ('published', 'draft'):
        raise ValueError('Status must be published or draft')
    fields['Author'] = fields.get('Author') or 'Madison Austin'
    fields['body'] = '\n'.join(lines[divider + 1:]).strip()
    if not fields['body']:
        raise ValueError('add some article text below ---')
    fields['slug'] = re.sub(r'[^a-z0-9]+', '-', filename[:-4].lower()).strip('-')
    if not fields['slug']:
        raise ValueError('the filename must include a letter or number for its URL')
    return fields


def prepare_image(post, root):
    post['image_url'] = None
    if not post.get('Image'):
        return
    path = post['Image'].replace('\\', '/').removeprefix('/')
    if path.startswith('notes/'):
        path = path[len('notes/'):]
    parts = path.split('/')
    if parts[0] != 'images' or any(part in ('', '.', '..') for part in parts):
        raise ValueError('Image must be a path inside notes/images, such as notes/images/hotel.jpg')
    image = root.joinpath(*parts)
    if not image.resolve().is_relative_to((root / 'images').resolve()):
        raise ValueError('Image must stay inside notes/images')
    if image.suffix.lower() not in ('.jpg', '.jpeg', '.png', '.webp', '.gif'):
        raise ValueError('Image must be a JPG, PNG, WebP, or GIF file')
    if not image.is_file():
        raise ValueError(f'Image file does not exist: notes/{path}')
    post['image_path'] = '/notes/' + quote(path, safe='/')
    post['image_url'] = 'https://yourluckyday.travel' + post['image_path']
    post['image_alt'] = post.get('Image Alt') or post['Title']


def render_inline_plain(text):
    """Escape ordinary text and render the small Markdown subset used in notes."""
    escaped = escape(text)
    return re.sub(r'\*\*([^*\n]+)\*\*', r'<strong>\1</strong>', escaped)


def render_inline(text):
    output = []
    end = 0
    for match in re.finditer(r'\[([^\]\n]+)\]\((https?://[^\s<>]+?)\)', text):
        output.append(render_inline_plain(text[end:match.start()]))
        output.append(f'<a href="{escape(match[2], quote=True)}" target="_blank" rel="noopener noreferrer">{render_inline_plain(match[1])}</a>')
        end = match.end()
    output.append(render_inline_plain(text[end:]))
    return ''.join(output)


def render_standard_blocks(text):
    output = []
    for block in re.split(r'\n\s*\n', text):
        if not block.strip():
            continue
        lines = block.splitlines()
        if len(lines) == 1 and block.startswith('## '):
            output.append(f'<h2 class="fw-bold">{render_inline(block[3:])}</h2>')
        elif len(lines) == 1 and (match := re.fullmatch(r'!\[([^\]\n]*)\]\((notes/images/[^\s()]+|https?://[^\s()]+)\)', block)):
            image_path = match[2].replace('\\\\', '/')
            if image_path.startswith('notes/images/'):
                image_file = Path(__file__).resolve().parent / image_path.removeprefix('notes/')
                if not image_file.is_file():
                    raise ValueError(f'Image file does not exist: {image_path}')
                if image_file.suffix.lower() not in ('.jpg', '.jpeg', '.png', '.webp', '.gif'):
                    raise ValueError(f'Image must be a JPG, PNG, WebP, or GIF file: {image_path}')
                image_path = '/' + image_path
            output.append(f'<img class="note-image note-inline-image" src="{escape(image_path, quote=True)}" alt="{escape(match[1])}" decoding="async">')
        elif all(line.startswith('- ') for line in lines):
            output.append('<ul>' + ''.join(f'<li>{render_inline(line[2:])}</li>' for line in lines) + '</ul>')
        else:
            output.append('<p>' + render_inline(' '.join(lines)) + '</p>')
    return '\n'.join(output)


def render_body(text):
    """Render article text, including optional native disclosure sections.

    A disclosure begins with ``??? Its label`` on a line by itself and ends
    with a closing ``???``. Its contents use the normal article format.
    """
    output = []
    ordinary = []
    toggle_label = None
    toggle_body = []

    def render_ordinary():
        if ordinary:
            # A toggle can leave a leading or trailing blank line in the
            # surrounding text. Trim it so the first following heading still
            # begins a heading block rather than a paragraph.
            output.append(render_standard_blocks('\n'.join(ordinary).strip()))
            ordinary.clear()

    for line in text.splitlines():
        if toggle_label is None and line.startswith('??? '):
            render_ordinary()
            toggle_label = line[4:].strip()
            if not toggle_label:
                raise ValueError('add a label after ??? for a toggle section')
            toggle_body = []
        elif toggle_label is not None and line.strip() == '???':
            output.append('<details class="note-toggle"><summary>'
                          + render_inline(toggle_label)
                          + '<span class="note-toggle-icon" aria-hidden="true"></span></summary>'
                          + '<div class="note-toggle-content">'
                          + render_standard_blocks('\n'.join(toggle_body).strip())
                          + '</div></details>')
            toggle_label = None
            toggle_body = []
        elif toggle_label is not None:
            toggle_body.append(line)
        else:
            ordinary.append(line)
    if toggle_label is not None:
        raise ValueError('close each toggle section with ??? on its own line')
    render_ordinary()
    return '\n'.join(part for part in output if part)


def byline(post):
    day = post['date']
    author = escape(post['Author'])
    if post['Author'] == 'Madison Austin':
        author = f'<a rel="author" href="/#about">{author}</a>'
    published = ''
    if day:
        label = f'{day:%B} {day.day}, {day.year}'
        published = (f'<span class="note-published">Published '
                     f'<time datetime="{day.isoformat()}">{label}</time></span>')
    updated = ''
    if post['updated'] and (day is None or post['updated'] > day):
        last = post['updated']
        updated = (f'<span class="note-updated">Updated '
                   f'<time datetime="{last.isoformat()}">{last:%B} {last.day}, {last.year}</time></span>')
    return f'<p class="note-meta"><span class="note-author">{author}</span>{published}{updated}</p>'


def article_metadata(post, url):
    author = {'@type': 'Person', 'name': post['Author']}
    if post['Author'] == 'Madison Austin':
        author['url'] = 'https://yourluckyday.travel/#about'
    graph = {'@context': 'https://schema.org', '@graph': [
        {'@type': 'Article', '@id': url + '#article', 'mainEntityOfPage': url,
         'headline': post['Title'], 'description': post['Summary'], 'inLanguage': 'en-US',
         'author': author, 'publisher': {'@type': 'Organization', 'name': 'Your Lucky Day', 'url': 'https://yourluckyday.travel/'}},
        {'@type': 'BreadcrumbList', 'itemListElement': [
            {'@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': 'https://yourluckyday.travel/'},
            {'@type': 'ListItem', 'position': 2, 'name': 'Travel Notes', 'item': 'https://yourluckyday.travel/notes/'},
            {'@type': 'ListItem', 'position': 3, 'name': post['Title'], 'item': url}]}]}
    metadata = ''
    if post.get('image_url'):
        graph['@graph'][0]['image'] = post['image_url']
    if post['date']:
        graph['@graph'][0]['datePublished'] = post['date'].isoformat()
        metadata += f'<meta property="article:published_time" content="{post["date"].isoformat()}">\n'
    if post['updated']:
        graph['@graph'][0]['dateModified'] = post['updated'].isoformat()
        metadata += f'<meta property="article:modified_time" content="{post["updated"].isoformat()}">\n'
    data = json.dumps(graph, ensure_ascii=False).replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
    return metadata + f'<script type="application/ld+json">{data}</script>\n'


def page(template, title, description, url, content, author='Madison Austin', kind='website', post=None):
    image_url = 'https://yourluckyday.travel/branding/assets/SEO%20Card.png'
    image_alt = 'Your Lucky Day — Travel Planning & Discovery, with a mountain backdrop'
    image_details = ('<meta property="og:image:type" content="image/png">\n'
                     '    <meta property="og:image:width" content="1200">\n'
                     '    <meta property="og:image:height" content="630">')
    if post and post.get('image_url'):
        image_url = post['image_url']
        image_alt = post['image_alt']
        image_details = ''
    values = {'TITLE': escape(title), 'DESCRIPTION': escape(description), 'URL': escape(url),
              'CONTENT': content, 'AUTHOR': escape(author), 'TYPE': kind,
              'IMAGE_URL': escape(image_url), 'IMAGE_ALT': escape(image_alt), 'IMAGE_DETAILS': image_details}
    return re.sub(r'\{\{(TITLE|DESCRIPTION|URL|CONTENT|AUTHOR|TYPE|IMAGE_URL|IMAGE_ALT|IMAGE_DETAILS)\}\}', lambda match: values[match[1]], template)


def build(root):
    root = root.resolve()
    sources = root / 'posts'
    if not sources.is_dir():
        raise ValueError('The posts folder is missing')
    files = []
    for path in sorted(sources.iterdir()):
        if not path.is_file() or path.suffix.lower() != '.txt' or path.name.lower() == 'template.txt':
            continue
        files.append(path.name)
    posts = []
    slugs = {}
    # Validate every source before changing any generated page.
    for filename in files:
        try:
            post = parse_post((root / 'posts' / filename).read_text(encoding='utf-8-sig'), filename)
            prepare_image(post, root)
        except (ValueError, OSError) as error:
            raise ValueError(f'{filename}: {error}') from error
        if post['Status'] == 'published':
            if post['slug'] in slugs:
                raise ValueError(f'{filename} and {slugs[post["slug"]]} produce the same URL; rename one file')
            slugs[post['slug']] = filename
            posts.append(post)
    posts.sort(key=lambda post: (post['order'] is None, post['order'] or 0,
                                 -post['date'].toordinal() if post['date'] else 0, post['slug']))
    template = (root / 'page-template.html').read_text(encoding='utf-8')
    outputs = {}
    cards = []
    for post in posts:
        route = f'/notes/note/{post["slug"]}/'
        article_image = (f'<img class="note-image" src="{escape(post["image_path"])}" '
                         f'alt="{escape(post["image_alt"])}" decoding="async">' if post['image_url'] else '')
        content = ('<article class="note-article"><nav class="note-breadcrumbs" aria-label="Breadcrumb">'
                   '<a href="/">Home</a> <span aria-hidden="true">/</span> <a href="/notes/">Travel Notes</a>'
                   f' <span aria-hidden="true">/</span> <span aria-current="page">{escape(post["Title"])}</span></nav>'
                   f'<h1 class="note-title">{escape(post["Title"])}</h1><div class="note-meta-row">{byline(post)}'
                   '<div class="note-share"><button type="button" class="note-share-button" hidden>'
                   'Share <i class="fa-solid fa-paper-plane" aria-hidden="true"></i></button>'
                   '<span class="note-share-status" role="status"></span>'
                   '<div class="note-share-fallback" hidden><label for="article-share-url">Copy this article link:</label>'
                   '<input id="article-share-url" type="url" readonly></div></div></div>'
                   f'<p class="note-summary">{escape(post["Summary"])}</p>'
                   f'{article_image}'
                   f'<div class="note-body">{render_body(post["body"])}</div>'
                   '<aside class="note-inquiry" aria-labelledby="note-inquiry-heading">'
                   '<h2 id="note-inquiry-heading">Have a trip in mind?</h2>'
                   '<p>Tell me what you’re thinking. I’ll get back to you within 24 hours of receiving your inquiry.</p>'
                   '<a class="btn btn-brand-primary" href="/inquiry/">Start your travel inquiry '
                   '<span class="arrow-icon" aria-hidden="true"></span></a></aside></article>')
        outputs[root / 'note' / post['slug'] / 'index.html'] = page(template, post['Title'] + ' | Your Lucky Day', post['Summary'],
                                                        'https://yourluckyday.travel' + route, content, post['Author'], 'article', post).replace(
                                                            '  </head>', article_metadata(post, 'https://yourluckyday.travel' + route)
                                                            + '<script src="/notes/share.js" defer></script>\n  </head>')
        cards.append(f'<article class="note-card"><h2><a href="{route}">{escape(post["Title"])}</a></h2>'
                     f'{byline(post)}<p>{escape(post["Summary"])}</p></article>')
    intro = ('<div class="notes-intro"><p class="section-eyebrow">From Madison Austin</p><h1>Travel notes.</h1>'
             '<p>Hotels, places, and the choices that shape a trip. Here’s how I think about them.</p></div>')
    listing = '<div class="notes-grid">' + '\n'.join(cards) + '</div>' if cards else '<p>My first travel notes are on the way. Check back soon.</p>'
    # Keep previously shared query-string links working; reading articles needs no JS.
    redirect = ('<script>const p = new URLSearchParams(location.search).get("post");'
                'if (p && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p)) '
                'location.replace("/notes/note/" + p + "/" + location.hash);</script>')
    outputs[root / 'index.html'] = page(template, 'Travel Notes | Your Lucky Day',
                                      'Travel planning notes from Madison Austin: hotels, destinations, and the decisions that shape a trip.',
                                      'https://yourluckyday.travel/notes/', intro + listing + redirect)
    stale = []
    for path in [*root.glob('*/index.html'), *root.glob('note/*/index.html')]:
        if path not in outputs and MARKER in path.read_text(encoding='utf-8'):
            stale.append(path)
    for path in [*outputs, *stale]:
        if not path.resolve().is_relative_to(root):
            raise ValueError(f'Output is outside the notes folder: {path}')
        if path.exists() and path != root / 'index.html' and MARKER not in path.read_text(encoding='utf-8'):
            raise ValueError(f'Refusing to overwrite a manually created page: {path}')
    for path, html in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html, encoding='utf-8')
    for path in stale:
        path.unlink()  # Only this generator's marked HTML files; no recursive deletion.
        if not any(path.parent.iterdir()):
            path.parent.rmdir()  # Remove only the now-empty generated article folder.
    namespace = 'http://www.sitemaps.org/schemas/sitemap/0.9'
    ET.register_namespace('', namespace)
    sitemap = ET.Element(f'{{{namespace}}}urlset')
    for route, modified in [('/notes/', None), *[(f'/notes/note/{post["slug"]}/', post['updated'].isoformat() if post['updated'] else None) for post in posts]]:
        entry = ET.SubElement(sitemap, f'{{{namespace}}}url')
        ET.SubElement(entry, f'{{{namespace}}}loc').text = 'https://yourluckyday.travel' + route
        if modified:
            ET.SubElement(entry, f'{{{namespace}}}lastmod').text = modified
    ET.ElementTree(sitemap).write(root / 'sitemap.xml', encoding='utf-8', xml_declaration=True)
    return posts


if __name__ == '__main__':
    try:
        posts = build(Path(__file__).parent)
        print(f'Built {len(posts)} article(s) and the Travel Notes overview.')
        for post in posts:
            print(f'https://yourluckyday.travel/notes/note/{post["slug"]}/')
        print('Publish the updated website files to make these pages live.')
    except (ValueError, OSError) as error:
        print(f'Could not build Travel Notes: {error}', file=sys.stderr)
        sys.exit(1)
