"""Generate shareable static pages from the text files in posts/."""
from datetime import date
from html import escape
from pathlib import Path
import re
import sys
import json
from xml.etree import ElementTree as ET

MARKER = '<!-- Generated by notes/build.py; edit the source .txt files instead. -->'


def parse_post(text, filename):
    lines = text.lstrip('\ufeff').splitlines()
    if '---' not in lines:
        raise ValueError('add a --- line between the header and article')
    divider = lines.index('---')
    fields = {}
    for line in lines[:divider]:
        if not line.strip():
            continue
        key, separator, value = line.partition(':')
        if not separator or key not in ('Title', 'Date', 'Updated', 'Summary', 'Author', 'Status') or key in fields:
            raise ValueError(f'invalid header: {line}')
        fields[key] = value.strip()
    for key in ('Title', 'Date', 'Summary'):
        if not fields.get(key):
            raise ValueError(f'add a {key}: line')
    if not re.fullmatch(r'\d{4}-\d{2}-\d{2}', fields['Date']):
        raise ValueError('Date must use YYYY-MM-DD')
    fields['date'] = date.fromisoformat(fields['Date'])
    fields['updated'] = fields['date']
    if fields.get('Updated'):
        if not re.fullmatch(r'\d{4}-\d{2}-\d{2}', fields['Updated']):
            raise ValueError('Updated must use YYYY-MM-DD')
        fields['updated'] = date.fromisoformat(fields['Updated'])
        if fields['updated'] < fields['date']:
            raise ValueError('Updated cannot be earlier than Date')
    fields['Status'] = fields.get('Status', 'published').lower()
    if fields['Status'] not in ('published', 'draft'):
        raise ValueError('Status must be published or draft')
    fields['Author'] = fields.get('Author') or 'Madison Austin'
    fields['body'] = '\n'.join(lines[divider + 1:]).strip()
    if not fields['body']:
        raise ValueError('add some article text below ---')
    fields['slug'] = re.sub(r'[^a-z0-9]+', '-', filename[:-4].lower()).strip('-')
    if not fields['slug']:
        raise ValueError('the filename must include a letter or number for its URL')
    return fields


def render_body(text):
    output = []
    for block in re.split(r'\n\s*\n', text):
        lines = block.splitlines()
        if len(lines) == 1 and block.startswith('## '):
            output.append(f'<h2>{escape(block[3:])}</h2>')
        elif all(line.startswith('- ') for line in lines):
            output.append('<ul>' + ''.join(f'<li>{escape(line[2:])}</li>' for line in lines) + '</ul>')
        else:
            output.append('<p>' + escape(' '.join(lines)) + '</p>')
    return '\n'.join(output)


def byline(post):
    day = post['date']
    label = f'{day:%B} {day.day}, {day.year}'
    author = escape(post['Author'])
    if post['Author'] == 'Madison Austin':
        author = f'<a rel="author" href="/#about">{author}</a>'
    updated = ''
    if post['updated'] > day:
        last = post['updated']
        updated = f' · Updated <time datetime="{last.isoformat()}">{last:%B} {last.day}, {last.year}</time>'
    return f'<p class="note-meta">{author} · Published <time datetime="{day.isoformat()}">{label}</time>{updated}</p>'


def article_metadata(post, url):
    author = {'@type': 'Person', 'name': post['Author']}
    if post['Author'] == 'Madison Austin':
        author['url'] = 'https://yourluckyday.travel/#about'
    graph = {'@context': 'https://schema.org', '@graph': [
        {'@type': 'Article', '@id': url + '#article', 'mainEntityOfPage': url,
         'headline': post['Title'], 'description': post['Summary'], 'inLanguage': 'en-US',
         'datePublished': post['Date'], 'dateModified': post['updated'].isoformat(),
         'author': author, 'publisher': {'@type': 'Organization', 'name': 'Your Lucky Day', 'url': 'https://yourluckyday.travel/'}},
        {'@type': 'BreadcrumbList', 'itemListElement': [
            {'@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': 'https://yourluckyday.travel/'},
            {'@type': 'ListItem', 'position': 2, 'name': 'Travel Notes', 'item': 'https://yourluckyday.travel/notes/'},
            {'@type': 'ListItem', 'position': 3, 'name': post['Title'], 'item': url}]}]}
    data = json.dumps(graph, ensure_ascii=False).replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
    return (f'<meta property="article:published_time" content="{post["Date"]}">\n'
            f'<meta property="article:modified_time" content="{post["updated"].isoformat()}">\n'
            f'<script type="application/ld+json">{data}</script>\n')


def page(template, title, description, url, content, author='Madison Austin', kind='website'):
    values = {'TITLE': escape(title), 'DESCRIPTION': escape(description), 'URL': escape(url),
              'CONTENT': content, 'AUTHOR': escape(author), 'TYPE': kind}
    return re.sub(r'\{\{(TITLE|DESCRIPTION|URL|CONTENT|AUTHOR|TYPE)\}\}', lambda match: values[match[1]], template)


def build(root):
    root = root.resolve()
    sources = root / 'posts'
    if not sources.is_dir():
        raise ValueError('The posts folder is missing')
    files = []
    for path in sorted(sources.iterdir()):
        if not path.is_file() or path.suffix.lower() != '.txt' or path.name.lower() == 'template.txt':
            continue
        files.append(path.name)
    posts = []
    slugs = {}
    # Validate every source before changing any generated page.
    for filename in files:
        try:
            post = parse_post((root / 'posts' / filename).read_text(encoding='utf-8-sig'), filename)
        except (ValueError, OSError) as error:
            raise ValueError(f'{filename}: {error}') from error
        if post['Status'] == 'published':
            if post['slug'] in slugs:
                raise ValueError(f'{filename} and {slugs[post["slug"]]} produce the same URL; rename one file')
            slugs[post['slug']] = filename
            posts.append(post)
    posts.sort(key=lambda post: (-post['date'].toordinal(), post['slug']))
    template = (root / 'page-template.html').read_text(encoding='utf-8')
    outputs = {}
    cards = []
    for post in posts:
        route = f'/notes/note/{post["slug"]}/'
        content = ('<article class="note-article"><nav class="note-breadcrumbs" aria-label="Breadcrumb">'
                   '<a href="/">Home</a> <span aria-hidden="true">/</span> <a href="/notes/">Travel Notes</a>'
                   f' <span aria-hidden="true">/</span> <span aria-current="page">{escape(post["Title"])}</span></nav>'
                   f'<h1 class="note-title">{escape(post["Title"])}</h1><div class="note-meta-row">{byline(post)}'
                   '<div class="note-share"><button type="button" class="note-share-button" hidden>Share this article</button>'
                   '<span class="note-share-status" role="status"></span>'
                   '<div class="note-share-fallback" hidden><label for="article-share-url">Copy this article link:</label>'
                   '<input id="article-share-url" type="url" readonly></div></div></div>'
                   f'<p class="note-summary">{escape(post["Summary"])}</p>'
                   f'<div class="note-body">{render_body(post["body"])}</div>'
                   '<aside class="note-inquiry" aria-labelledby="note-inquiry-heading">'
                   '<h2 id="note-inquiry-heading">Have a trip in mind?</h2>'
                   '<p>Tell me what you’re thinking. I’ll get back to you within 24 hours of receiving your inquiry.</p>'
                   '<a class="btn btn-brand-primary" href="/inquiry/">Start your travel inquiry '
                   '<span class="arrow-icon" aria-hidden="true"></span></a></aside></article>')
        outputs[root / 'note' / post['slug'] / 'index.html'] = page(template, post['Title'] + ' | Your Lucky Day', post['Summary'],
                                                        'https://yourluckyday.travel' + route, content, post['Author'], 'article').replace(
                                                            '  </head>', article_metadata(post, 'https://yourluckyday.travel' + route)
                                                            + '<script src="/notes/share.js" defer></script>\n  </head>')
        cards.append(f'<article class="note-card"><h2><a href="{route}">{escape(post["Title"])}</a></h2>'
                     f'{byline(post)}<p>{escape(post["Summary"])}</p></article>')
    intro = ('<div class="notes-intro"><p class="section-eyebrow">From Madison Austin</p><h1>Travel notes.</h1>'
             '<p>Hotels, places, and the choices that shape a trip. Here’s how I think about them.</p></div>')
    listing = '<div class="notes-grid">' + '\n'.join(cards) + '</div>' if cards else '<p>My first travel notes are on the way. Check back soon.</p>'
    # Keep previously shared query-string links working; reading articles needs no JS.
    redirect = ('<script>const p = new URLSearchParams(location.search).get("post");'
                'if (p && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p)) '
                'location.replace("/notes/note/" + p + "/" + location.hash);</script>')
    outputs[root / 'index.html'] = page(template, 'Travel Notes | Your Lucky Day',
                                      'Travel planning notes from Madison Austin: hotels, destinations, and the decisions that shape a trip.',
                                      'https://yourluckyday.travel/notes/', intro + listing + redirect)
    stale = []
    for path in [*root.glob('*/index.html'), *root.glob('note/*/index.html')]:
        if path not in outputs and MARKER in path.read_text(encoding='utf-8'):
            stale.append(path)
    for path in [*outputs, *stale]:
        if not path.resolve().is_relative_to(root):
            raise ValueError(f'Output is outside the notes folder: {path}')
        if path.exists() and path != root / 'index.html' and MARKER not in path.read_text(encoding='utf-8'):
            raise ValueError(f'Refusing to overwrite a manually created page: {path}')
    for path, html in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html, encoding='utf-8')
    for path in stale:
        path.unlink()  # Only this generator's marked HTML files; no recursive deletion.
        if not any(path.parent.iterdir()):
            path.parent.rmdir()  # Remove only the now-empty generated article folder.
    namespace = 'http://www.sitemaps.org/schemas/sitemap/0.9'
    ET.register_namespace('', namespace)
    sitemap = ET.Element(f'{{{namespace}}}urlset')
    for route, modified in [('/notes/', None), *[(f'/notes/note/{post["slug"]}/', post['updated'].isoformat()) for post in posts]]:
        entry = ET.SubElement(sitemap, f'{{{namespace}}}url')
        ET.SubElement(entry, f'{{{namespace}}}loc').text = 'https://yourluckyday.travel' + route
        if modified:
            ET.SubElement(entry, f'{{{namespace}}}lastmod').text = modified
    ET.ElementTree(sitemap).write(root / 'sitemap.xml', encoding='utf-8', xml_declaration=True)
    return posts


if __name__ == '__main__':
    try:
        posts = build(Path(__file__).parent)
        print(f'Built {len(posts)} article(s) and the Travel Notes overview.')
        for post in posts:
            print(f'https://yourluckyday.travel/notes/note/{post["slug"]}/')
        print('Publish the updated website files to make these pages live.')
    except (ValueError, OSError) as error:
        print(f'Could not build Travel Notes: {error}', file=sys.stderr)
        sys.exit(1)
